get_filename_component(CXX_COMPILER_NAME ${CMAKE_CXX_COMPILER} NAME)

if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  LogMessage("Setting the gcc compiler flags ...")
  if(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
    message(FATAL_ERROR "Windows builds are currently not supported")
  else()
    set(COMMON_FLAGS "-Wall -Wextra")
    if(CMAKE_BUILD_TYPE STREQUAL "Debug")
      set(DEBUG_FLAGS "-g")
      set(OPTIM_FLAG "-O0")
      set(LINKER_FLAGS "")
    elseif(CMAKE_BUILD_TYPE STREQUAL "Release")
      set(DEBUG_FLAGS "")
      set(OPTIM_FLAG "-O3 -march=native -flto")
      set(LINKER_FLAGS "-flto")
    else()
      message(FATAL_ERROR "Unknown CMAKE_BUILD_TYPE: ${CMAKE_BUILD_TYPE}")
    endif()
    set(CXX_FLAGS "${COMMON_CXX_FLAGS} ${OPTIM_CXX_FLAGS} ${DEBUG_CXX_FLAGS}")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CXX_FLAGS}")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}")
  endif()
elseif(CXX_COMPILER_NAME MATCHES "i.*")
  message(FATAL_ERROR "Intel compiler is currently not supported")
else()
  message(FATAL_ERROR "Unknown compiler: ${CXX_COMPILER_NAME}")
endif()
